### PR TITLE
don't test rails 7 with old rubies

### PR DESCRIPTION
**Pull request by gregmolnar**

### CODE REVIEW

**Comment by davidwessman** [comment]
Looks good 🙂

**Comment by simi** [comment]
Any reason to opt-out Ruby 2.7 as well? It is still supported on Rails 7.

**Comment by davidwessman** [comment]
> Any reason to opt-out Ruby 2.7 as well? It is still supported on Rails 7.

I added the Ruby 3.0 and 3.1 as separate to only test it on the latest Rails (since it was not present in the Travis-suite)

**Comment by gregmolnar** [comment]
> Any reason to opt-out Ruby 2.7 as well? It is still supported on Rails 7.

I added it in #150

**Pull request merged**
