### PR TITLE
Support Rails 6.1

### PR DESCRIPTION
**Pull request by jansi-z**
I believe this should be pretty straightforward, I couldn't find any breaking changes in the ActiveRecord changelog. I'll open a PR.

Disclaimer: it's my first time contributing to an open source project, let me know if I'm doing something wrong!

### CODE REVIEW

**Comment by bensheldon** [comment]
@jansi-z Thank you! It looks like Travis isn't yet running the tests for the new Rails 6.1 gemfile you added. I think that can be done by updating the Travis config too: https://github.com/textacular/textacular/blob/767273e7b2e8b42acf84b7433a885d8fe82b94fd/.travis.yml#L17-L22

**Comment by jansi-z** [comment]
@bensheldon Thanks for that! I added the new gemfile to the Travis config, and it looks like it passes. Is there anything else I should do?

**Comment by bensheldon** [comment]
@jansi-z that looks like everything I'm aware of. Unfortunately I'm not a maintainer (just a very interested consumer of your patch).

**Comment by jansi-z** [comment]
@bensheldon Thanks either way!

@gregmolnar Hope you don't mind me tagging you here, I thought I'd give you a shout since you added the Rails 6 patch. Could you take a lookt at this PR?

**Comment by gregmolnar** [comment]
@jansi-z Thanks for your contribution!
I didn't get a notification about this PR s thank's for tagging me. I am merging this and will release a new version shortly.

**Pull request merged**
