### PR TITLE
rebased #46

### PR DESCRIPTION
**Pull request by simi**

### CODE REVIEW

**Comment by benhamill** [comment]
Cool. Can you update the Changelog (see [the contribution guidelines](https://github.com/textacular/textacular/blob/master/CONTRIBUTING.md)?

**Comment by simi** [comment]
sure, also some tests are red on CI (for 3-2 gemfile) so I need to investigate how to fix that

**Comment by simi** [comment]
@benhamill I can't reproduce CI fails locally :( Can you try please?

**Comment by benhamill** [comment]
I'll see if I can have a look this evening. Unless someone beats me to it. :)

**Comment by gregmolnar** [comment]
I managed to reproduce the failure locally and fixed the issue in a new PR. Waiting to see if Travis is happy with my fix.
Thank you @simi

**Comment by gregmolnar** [comment]
My fix introduced even more errors :). The problem is actually with the test not with the code. Before my change the numericality of the rank was tested, but it looks like sometimes the rank is returned as a string so that fails. My thought was, if I convert it to a float, it should make the test suite happy, but apparently that's not a good solution. I will have a deeper look of how that part of the code works.

**Comment by simi** [comment]
OK, I'll take a look. Can you provide me some steps how to reproduce that?

**Comment by gregmolnar** [comment]
@simi I already tracked down the error. Actually instead of `Numeric` we should test for `truthy` because anything else than `nil` means the code works as expected. I pushed a fix on the other branch and waiting for travis.
I just simply run the tests and I got the same errors as I saw on travis. I guess it is some system differences between your setup and mine. For some reason on my machine AR 3 returns a string for the rank but I guess on yours it returns float. Just so it is even more fun, when I did an explicit float conversion in the test, it was passing with each gemfile locally but there were failures on Travis.
Thanks again for your help!

**Pull request closed without merging**
