### PR TITLE
Fix fuzzy search when field contains multiple strings (like a sentence). Was returning empty results.

### PR DESCRIPTION
**Pull request by dotnofoolin**

### CODE REVIEW

**Comment by dotnofoolin** [comment]
Updated by merging in master to fix conflicts and make my branch compatible with Rails 5.2+.

**Comment by dotnofoolin** [comment]
I know it's been 3 years, but any chance this might get merged one day? Is there something that needs to be addressed first?

**Comment by gregmolnar** [comment]
Thanks for the reminder, I totally forgot about this. It is merged now, thanks for your contribution!

**Comment by simi** [comment]
@gregmolnar can you explain this PR? This moves `fuzzy_search` (originally using `pg_trgm` extension and `#` operator as described at https://www.postgresql.org/docs/14/pgtrgm.html#PGTRGM-OP-TABLE and [README](https://github.com/textacular/textacular#usage) of this project) to pattern matching (using `ILIKE` operator as described at https://www.postgresql.org/docs/14/functions-matching.html).

That is compatibility breaking change and it seems it wasn't intended. This change is not even mentioned in changelog - https://github.com/textacular/textacular/blob/master/CHANGELOG.md#550.

Would it be possible to revert this and release again version using proper fuzzy matching and add ILIKE based search as separate method if needed?

**Comment by gregmolnar** [comment]
@simi you are absolutely right, I have no idea where my mind was when I merged this. 
@dotnofoolin I assume you issue is rooted at `pg_trgm.similarity_threshold` is being set too high for your requirement and that's why you didn't get the results you are after. The spec you added fails because of that being at the default `0.3`, if you lower that, the spec passes. 
I am reverting this and cutting a new version. @simi thanks again for catching this.

**Comment by dotnofoolin** [comment]
@gregmolnar Thanks for the info about the threshold. I believe that when I discovered that `fuzzy_search` wasn't working as expected, it was because I'm using `concat_ws` to build a single string from multiple columns. Searching against this large string for a single word, or multiple small words, wasn't hitting the 30% threshold. 

Where do you suggest I add `ActiveRecord::Base.connection.execute("SELECT set_limit(0.1);")`? Create a new `config/initializers` file for it?

**Comment by gregmolnar** [comment]
@dotnofoolin the best is to set it in the `postgresql.conf` globally with `pg_trgm.similarity_threshold = 0.1`. Or you can set it on a database level with:
```
alter database DATABASE_NAME set pg_trgm.similarity_threshold = 0.1;
```
You can execute the above from a migration, as it needs to be run only once.

**Pull request merged**
